name: Deploy to WordPress.org
on:
  push
  
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
#     - name: Build
#       run: |
#         npm install
#         npm run build
#     - name: WordPress Plugin Deploy
#       id: deploy
#       uses: 10up/action-wordpress-plugin-deploy@stable
#       with:
#         generate-zip: true
#       env:
#         SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
#         SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        
        
#     - name: Upload release asset
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ github.event.release.upload_url }}
#         asset_path: ${{ steps.deploy.outputs.zip-path }}
#         asset_name: ${{ github.event.repository.name }}.zip
#         asset_content_type: application/zip
  
  
    - name: conventional changelog action
      id: changelog
      # https://github.com/TriPSs/conventional-changelog-action
      uses: TriPSs/conventional-changelog-action@latest
      with:
        # you can also create separate token to trace action
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: create release
      # https://github.com/actions/create-release
      uses: softprops/action-gh-release@v1
      if: ${{steps.changelog.outputs.skipped == 'false'}}
      env:
        # This token is provided by Actions, you do not need to create your own token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{steps.changelog.outputs.clean_changelog}}
          draft: false
          prerelease: false
